# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: packlight_development

test:
  <<: *default
  database: packlight_test

production:
  primary:
    <<: *default
    database: packlight_production
    host: <%= ENV.fetch("DB_HOST") %>
    username: <%= ENV.fetch("DB_USERNAME") %>
    password: <%= ENV.fetch("DB_PASSWORD") %>
  cache:
    <<: *default
    database: packlight_cache
    host: <%= ENV.fetch("DB_HOST") %>
    username: <%= ENV.fetch("DB_USERNAME") %>
    password: <%= ENV.fetch("DB_PASSWORD") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: packlight_queue
    host: <%= ENV.fetch("DB_HOST") %>
    username: <%= ENV.fetch("DB_USERNAME") %>
    password: <%= ENV.fetch("DB_PASSWORD") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: packlight_cable
    host: <%= ENV.fetch("DB_HOST") %>
    username: <%= ENV.fetch("DB_USERNAME") %>
    password: <%= ENV.fetch("DB_PASSWORD") %>
    migrations_paths: db/cable_migrate
