# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: packlight_development

test:
  <<: *default
  database: packlight_test

production:
  primary:
    <<: *default
    database: packlight_production
    url: <%= ENV.fetch("DATABASE_URL") %>
  cache:
    <<: *default
    database: packlight_cache
    url: <%= ENV.fetch("DATABASE_URL") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: packlight_queue
    url: <%= ENV.fetch("DATABASE_URL") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: packlight_cable
    url: <%= ENV.fetch("DATABASE_URL") %>
    migrations_paths: db/cable_migrate
